/*
 * This source file was generated by the Gradle 'init' task
 */
package boatsimulator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import edu.macalester.graphics.Point;
import edu.macalester.graphics.CanvasWindow;
import edu.macalester.graphics.Image;

class BoatSimulatorTest {
    @Test
    public void testSomething() {
        Point point = new Point(1,1);
        // BoatSimulator sim = new BoatSimulator();

    }
    
    public void testImageRotation(){
        CanvasWindow canvas = new CanvasWindow("please", 800, 800);
        Image image = new Image("SloopScaled.png");
        canvas.add(image);
        image.rotateBy(100);
    }
    BoatSimulatorTest(){
        testImageRotation();
    }
}
